/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Story API
 * Branching story node API for Deadline & Adhan
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetNextStoryNodeBody
} from './model';





/**
 * @summary Get first story node
 */
export type getStoryStartResponse200 = {
  data: void
  status: 200
}

export type getStoryStartResponse404 = {
  data: void
  status: 404
}

export type getStoryStartResponseSuccess = (getStoryStartResponse200) & {
  headers: Headers;
};
export type getStoryStartResponseError = (getStoryStartResponse404) & {
  headers: Headers;
};

export type getStoryStartResponse = (getStoryStartResponseSuccess | getStoryStartResponseError)

export const getGetStoryStartUrl = () => {


  

  return `/api/story/start`
}

export const getStoryStart = async ( options?: RequestInit): Promise<getStoryStartResponse> => {
  
  const res = await fetch(getGetStoryStartUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStoryStartResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStoryStartResponse
}
  




export const getGetStoryStartQueryKey = () => {
    return [
    `/api/story/start`
    ] as const;
    }

    
export const getGetStoryStartQueryOptions = <TData = Awaited<ReturnType<typeof getStoryStart>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryStart>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoryStartQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStoryStart>>> = ({ signal }) => getStoryStart({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStoryStart>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoryStartQueryResult = NonNullable<Awaited<ReturnType<typeof getStoryStart>>>
export type GetStoryStartQueryError = void


export function useGetStoryStart<TData = Awaited<ReturnType<typeof getStoryStart>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryStart>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoryStart>>,
          TError,
          Awaited<ReturnType<typeof getStoryStart>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoryStart<TData = Awaited<ReturnType<typeof getStoryStart>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryStart>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoryStart>>,
          TError,
          Awaited<ReturnType<typeof getStoryStart>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoryStart<TData = Awaited<ReturnType<typeof getStoryStart>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryStart>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get first story node
 */

export function useGetStoryStart<TData = Awaited<ReturnType<typeof getStoryStart>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryStart>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoryStartQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get story node by id
 */
export type getStoryNodeResponse200 = {
  data: void
  status: 200
}

export type getStoryNodeResponse404 = {
  data: void
  status: 404
}

export type getStoryNodeResponseSuccess = (getStoryNodeResponse200) & {
  headers: Headers;
};
export type getStoryNodeResponseError = (getStoryNodeResponse404) & {
  headers: Headers;
};

export type getStoryNodeResponse = (getStoryNodeResponseSuccess | getStoryNodeResponseError)

export const getGetStoryNodeUrl = (id: number,) => {


  

  return `/api/story/${id}`
}

export const getStoryNode = async (id: number, options?: RequestInit): Promise<getStoryNodeResponse> => {
  
  const res = await fetch(getGetStoryNodeUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStoryNodeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStoryNodeResponse
}
  




export const getGetStoryNodeQueryKey = (id: number,) => {
    return [
    `/api/story/${id}`
    ] as const;
    }

    
export const getGetStoryNodeQueryOptions = <TData = Awaited<ReturnType<typeof getStoryNode>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryNode>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStoryNodeQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStoryNode>>> = ({ signal }) => getStoryNode(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStoryNode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStoryNodeQueryResult = NonNullable<Awaited<ReturnType<typeof getStoryNode>>>
export type GetStoryNodeQueryError = void


export function useGetStoryNode<TData = Awaited<ReturnType<typeof getStoryNode>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryNode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoryNode>>,
          TError,
          Awaited<ReturnType<typeof getStoryNode>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoryNode<TData = Awaited<ReturnType<typeof getStoryNode>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryNode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStoryNode>>,
          TError,
          Awaited<ReturnType<typeof getStoryNode>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStoryNode<TData = Awaited<ReturnType<typeof getStoryNode>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryNode>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get story node by id
 */

export function useGetStoryNode<TData = Awaited<ReturnType<typeof getStoryNode>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStoryNode>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStoryNodeQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get next story node by choice
 */
export type getNextStoryNodeResponse200 = {
  data: void
  status: 200
}

export type getNextStoryNodeResponse404 = {
  data: void
  status: 404
}

export type getNextStoryNodeResponseSuccess = (getNextStoryNodeResponse200) & {
  headers: Headers;
};
export type getNextStoryNodeResponseError = (getNextStoryNodeResponse404) & {
  headers: Headers;
};

export type getNextStoryNodeResponse = (getNextStoryNodeResponseSuccess | getNextStoryNodeResponseError)

export const getGetNextStoryNodeUrl = () => {


  

  return `/api/story/next`
}

export const getNextStoryNode = async (getNextStoryNodeBody: GetNextStoryNodeBody, options?: RequestInit): Promise<getNextStoryNodeResponse> => {
  
  const res = await fetch(getGetNextStoryNodeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      getNextStoryNodeBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getNextStoryNodeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNextStoryNodeResponse
}
  



export const getGetNextStoryNodeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getNextStoryNode>>, TError,{data: GetNextStoryNodeBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof getNextStoryNode>>, TError,{data: GetNextStoryNodeBody}, TContext> => {

const mutationKey = ['getNextStoryNode'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getNextStoryNode>>, {data: GetNextStoryNodeBody}> = (props) => {
          const {data} = props ?? {};

          return  getNextStoryNode(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetNextStoryNodeMutationResult = NonNullable<Awaited<ReturnType<typeof getNextStoryNode>>>
    export type GetNextStoryNodeMutationBody = GetNextStoryNodeBody
    export type GetNextStoryNodeMutationError = void

    /**
 * @summary Get next story node by choice
 */
export const useGetNextStoryNode = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getNextStoryNode>>, TError,{data: GetNextStoryNodeBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getNextStoryNode>>,
        TError,
        {data: GetNextStoryNodeBody},
        TContext
      > => {
      return useMutation(getGetNextStoryNodeMutationOptions(options), queryClient);
    }
    
