/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Story API
 * Branching story node API for Deadline & Adhan
 * OpenAPI spec version: 1.0
 */

export type GetNextStoryNodeBody = {
  /**
   * ID of next node, or null for end of story
   * @nullable
   */
  next_id: number | null;
};
